# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
app = 'hr-copilot-staging'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[http_service]
  internal_port = 8000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  # Note: commented out environments needs to placed in fly secrets
  # --> fly secrets --config fly.staging.toml set XXX=XXX
  # Secrets
  # TALENT_COPILOT_OPENAI_API_KEY
  # TALENT_COPILOT_DB_PASS
  # TALENT_COPILOT_AWS_SECRET_ACCESS_KEY
  # TALENT_COPILOT_AWS_ACCESS_KEY_ID = "AKIA2SQOZQO26332MXMC"
  # TALENT_COPILOT_TOGETHER_API_KEY
  # TALENT_COPILOT_REDIS_PASS

  # General
  TALENT_COPILOT_ENVIRONMENT = "staging"
  TALENT_COPILOT_VERSION = "0.1.0"

  # Sentry
  TALENT_COPILOT_SENTRY_DSN = "https://71e207a3b4d2fbe8ee032aa0d1470394@o4506761852551168.ingest.sentry.io/4506772487864320"

  # Redis
  TALENT_COPILOT_REDIS_HOST = "fly-redis-talent-copilot-staging.upstash.io"
  TALENT_COPILOT_REDIS_PORT = "6379"
  TALENT_COPILOT_REDIS_USER = "default"

  # DB
  TALENT_COPILOT_DB_HOST = "ep-cold-waterfall-a27rc1yh.eu-central-1.aws.neon.tech"
  TALENT_COPILOT_DB_PORT = "5432"
  TALENT_COPILOT_DB_USER = "leonardo.vida"
  TALENT_COPILOT_DB_BASE = "talent_copilot"
  TALENT_COPILOT_S3_BUCKET_NAME = "tc-staging-documents"
  TALENT_COPILOT_OPENAI_GPT_MODEL_NAME = "gpt-4-turbo-preview"
  TALENT_COPILOT_LLM_PROVIDER = "openai"

  # LLM
  TALENT_COPILOT_MODEL_TYPE = "openai" # this variable chooses between providers
  TALENT_COPILOT_OPENAI_SEED = "12345"
  TALENT_COPILOT_OPENAI_TEMPERATURE = "0.0"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
