name: Alembic Migration
description: Run alembic migration on AWS RDS

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.11"
  aws-region:
    description: "AWS region to use"
    required: true
    default: "eu-west-1"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install alembic psycopg2-binary

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}

    - name: Run Alembic migration
      shell: bash
      run: |
        alembic upgrade head
      env:
        DATABASE_URL: ${{ secrets.AWS_RDS_CONNECTION_STRING }}
