name: Deploy backend staging on Fly

on:
  push:
    branches:
      - main
    # Only run when something changes in 'backend/'
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: chartboost/ruff-action@v1
        with:
          src: "./backend"
          args: --select B

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    needs: lint-and-format
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy backend --config fly.staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
